site_name: My Docs
site_url: https://lakeeeeee.github.io/
theme:
  name: material

nav:
  - 首頁: index.adoc
  - 筆記: 
    - 物件導向程式設計: work/oop.adoc
    - ISO27001的「照」到底可以幹嘛: work/iso.adoc

plugins:
  - search
  - asciidoctor_backend:          # 注意外掛 key 名稱
      fail_on_error: false        # 有非致命錯誤時不擋 build（可改 true）
      safe_mode: safe
      attributes:                 # 可傳 Asciidoctor 屬性
        imagesdir: images
        sectanchors: true
        sectlinks: true
        source-highlighter: rouge

markdown_extensions:
  - admonition
  - toc:
      permalink: true
